{% set name = "safety" %}
{% set version = "1.8.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3016631e0dd17193d6cf12e8ed1af92df399585e8ee0e4b1300d9e7e32b54903

build:
  number: 0
  entry_points:
    - safety=safety.cli:cli
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  noarch: python

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - click >=6.0
    - dparse >=0.4.1
    - packaging
    - python
    - requests
    - setuptools

test:
  imports:
    - safety
  commands:
    - safety --help

about:
  home: https://pyup.io/safety
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Safety checks your installed dependencies for known security vulnerabilities.
  doc_url: https://pyup.io/docs
  dev_url: https://github.com/pyupio/safety

extra:
  recipe-maintainers:
    - jkornblum
