{% set version = "3.2.4" %}
{% set test_skips = "not validate_with_basic_policy_file" %}
{% set cov_fail_under = 52 %}

package:
  name: safety
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/safety/safety-{{ version }}.tar.gz
  sha256: bac0202016d736a2118057964a0e3983fa20ff2563fd103cac3f3ac1ed3fea11

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - safety=safety.cli:cli

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - authlib >=1.2.0
    - click >=8.0.2
    - dparse >=0.6.4b0
    - filelock >=3.12.2,<3.13
    - jinja2 >=3.1.0
    - marshmallow >=3.15.0
    - packaging >=21.0
    - pydantic >=1.10.12
    - python >=3.7
    - requests
    - rich
    - ruamel.yaml >=0.17.21
    - safety-schemas >=0.0.2
    - setuptools >=65.5.1
    - typer
    - typing_extensions >=4.7.1
    - urllib3 >=1.26.5

test:
  source_files:
    - tests
  requires:
    - coverage
    - git
    - pip
    - pytest
  imports:
    - safety
  commands:
    - pip check
    - safety --help
    - safety --version
    # as of 3.0.1, `test_utils.py` circular imports when not tested next to source
    - python -c "__import__('shutil').rmtree('tests/alerts')"
    - coverage run --source safety --branch -m pytest -vv --tb=long --color=yes -k "{{ test_skips }}"
    - coverage report --show-missing --skip-covered --fail-under={{ cov_fail_under }}

about:
  home: https://pyup.io/safety
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Safety checks your installed dependencies for known security vulnerabilities.
  doc_url: https://pyup.io/docs
  dev_url: https://github.com/pyupio/safety

extra:
  recipe-maintainers:
    - jkornblum
    - bollwyvl
