{% set version = "3.2.14" %}
{% set python_min = python_min | default("3.9") %}

{% set test_skips = "not (validate_with_basic_policy_file or debug_flag or generate_pass)" %}
{% set cov_fail_under = 49 %}
{% set min_safety_schema = "0.0.10" %}

package:
  name: safety
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/safety/safety-{{ version }}.tar.gz
  sha256: 7a45d88b1903c5b7c370eaeb6ca131a52f147e0b8a0b302265f82824ef92adc7

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  entry_points:
    - safety=safety.cli:cli

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=42
  run:
    - authlib >=1.2.0
    - click >=8.0.2
    - dparse >=0.6.4
    - filelock >=3.16.1,<3.17
    - jinja2 >=3.1.0
    - marshmallow >=3.15.0
    - packaging >=21.0
    - psutil >=6.1.0,<6.2
    - pydantic >=2.6.0,<2.10.0
    - python >={{ python_min }}
    - requests
    - rich
    - ruamel.yaml >=0.17.21
    - safety-schemas =={{ min_safety_schema }}
    - setuptools >=65.5.1
    - typer >=0.12.1
    - typing_extensions >=4.7.1
    - urllib3 >=1.26.5

test:
  source_files:
    - tests
  requires:
    - coverage
    - git
    - pip
    - python {{ python_min }}
    - pytest
    - safety-schemas =={{ min_safety_schema }}
  imports:
    - safety
  commands:
    - pip check
    - safety --help
    - safety --version
    # as of 3.0.1, `test_utils.py` circular imports when not tested next to source
    - python -c "__import__('shutil').rmtree('tests/alerts')"
    - coverage run --source safety --branch -m pytest -vv --tb=long --color=yes -k "{{ test_skips }}"
    - coverage report --show-missing --skip-covered --fail-under={{ cov_fail_under }}

about:
  home: https://pyup.io/safety
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Safety checks your installed dependencies for known security vulnerabilities.
  doc_url: https://pyup.io/docs
  dev_url: https://github.com/pyupio/safety

extra:
  recipe-maintainers:
    - jkornblum
    - bollwyvl
