{% set version = "3.0.0" %}

package:
  name: safety
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/safety/safety-{{ version }}.tar.gz
  sha256: e20eeb06add4d6d0c84c1915cd48f69174399365758de2e5c147a1ef637a1962

build:
  number: 0
  entry_points:
    - safety=safety.cli:cli
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - authlib >=1.2.0
    - click >=8.0.2
    - dparse >=0.6.4b0
    - jinja2 >=3.1.0
    - marshmallow >=3.15.0
    - packaging >=21.0
    - pydantic >=1.10.12,<2.0
    - python >=3.6
    - requests
    - rich
    - ruamel.yaml >=0.17.21
    - safety-schemas >=0.0.1
    - setuptools >=65.5.1
    - typer
    - typing-extensions >=4.7.1
    - urllib3 >=1.26.5

test:
  source_files:
    - tests
  requires:
    - coverage
    - git
    - pip
    - pytest
  imports:
    - safety
  commands:
    - pip check
    - safety --help
    - safety --version
    - coverage run --source=safety --branch -m pytest -vv --color=yes --tb=long
    - coverage report --show-missing --skip-covered --fail-under=100

about:
  home: https://pyup.io/safety
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Safety checks your installed dependencies for known security vulnerabilities.
  doc_url: https://pyup.io/docs
  dev_url: https://github.com/pyupio/safety

extra:
  recipe-maintainers:
    - jkornblum
    - bollwyvl
