{% set version = "3.0.1" %}

package:
  name: safety
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/safety/safety-{{ version }}.tar.gz
  sha256: 1f2000f03652f3a0bfc67f8fd1e98bc5723ccb76e15cb1bdd68545c3d803df01

build:
  number: 0
  entry_points:
    - safety=safety.cli:cli
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - authlib >=1.2.0
    - click >=8.0.2
    - dparse >=0.6.4b0
    - jinja2 >=3.1.0
    - marshmallow >=3.15.0
    - packaging >=21.0
    - pydantic >=1.10.12,<2.0
    - python >=3.6
    - requests
    - rich
    - ruamel.yaml >=0.17.21
    - safety-schemas >=0.0.1
    - setuptools >=65.5.1
    - typer
    - typing-extensions >=4.7.1
    - urllib3 >=1.26.5

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest
    - git
  imports:
    - safety
    - safety.alerts
    - safety.formatters
  commands:
    - pip check
    - safety --help
    - safety --version
    - pytest

about:
  home: https://pyup.io/safety
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Safety checks your installed dependencies for known security vulnerabilities.
  doc_url: https://pyup.io/docs
  dev_url: https://github.com/pyupio/safety

extra:
  recipe-maintainers:
    - jkornblum
    - bollwyvl
