# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 3.3.0

package:
  name: safety
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/safety/safety-${{ version }}.tar.gz
  sha256: 67f9f823120e42ff3f0f5fdba00d0547fb9c655bc77c179084b75bf961abcfae

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  python:
    entry_points:
      - safety = safety.cli:cli

requirements:
  host:
    - hatchling
    - pip
    - python ${{ python_min }}.*
  run:
    - authlib >=1.2.0
    - click >=8.0.2
    - dparse >=0.6.4
    - filelock >=3.16.1,<3.17
    - jinja2 >=3.1.0
    - marshmallow >=3.15.0
    - packaging >=21.0
    - psutil >=6.1.0,<6.2
    - pydantic >=2.6.0,<2.10.0
    - python >=${{ python_min }}
    - python-levenshtein >=0.25.1
    - requests
    - ruamel.yaml >=0.17.21
    - safety-schemas ==0.0.10
    - setuptools >=65.5.1
    - typer >=0.12.1
    - typing_extensions >=4.7.1

tests:
  - python:
      pip_check: true
      python_version: ${{ python_min }}.*
      imports: safety
  - files:
      recipe:
        - run_test.py
      source:
        - tests/
    requirements:
      run:
        - coverage
        - git
        - python ${{ python_min }}.*
        - pytest
        - safety-schemas ==${{ min_safety_schema }}
    script:
      - pip check
      - safety --help
      - safety --version
      - python run_test.py

about:
  license: MIT
  license_file: LICENSE
  summary: Safety checks your installed dependencies for known security vulnerabilities.
  homepage: https://pyup.io/safety
  repository: https://github.com/pyupio/safety
  documentation: https://pyup.io/docs

extra:
  recipe-maintainers:
    - jkornblum
    - bollwyvl
